version: "3.2"
services:
  api:
    image: dmytroch/game-back-end
    container_name: ws-api
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "4000:4000"